version: "3"
services:
  dynamodb:
    container_name: dynamodb
    image: misoca/dynamodb-local-persist
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/dynamodb:/home/dynamodblocal/db
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
  dynamodb-api:
    container_name: dynamodb-api
    build: src/DynamoDB-local-test-api/.
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development