version: '3.4'

services:
  dynamodb:
    image: misoca/dynamodb-local-persist
    ports:
      - "8000:8000"
    volumes:
      - ../../volumes/dynamodb:/home/dynamodblocal/db
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
  dynamodb-local-test-api:
    image: ${DOCKER_REGISTRY-}dynamodblocaltestapi
    build:
      context: .
      dockerfile: Dockerfile

